name: s3-deploy

on: 
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      dryrun_mode:
        description: 'set --dryrun flag'
        type: boolean 

jobs:
  deploy:
    name: Sync files to S3 Bucket
    # Run on self-hosted linux runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: S3 sync (dryrun mode)
        if: ${{ inputs.dryrun_mode }}
        run: sh -x deploy-dryrun.sh

      - name: S3 sync (for real)
        if: ${{ !inputs.dryrun_mode }} 
        run: sh -x deploy.sh

        