name: s3-deploy

on: 
  push:
    branches:    
      - main

jobs:
  s3-sync:
    name: Sync files to S3 Bucket
    needs: build
    # Run on self-hosted linux runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Sync files to S3 Bucket 
        run: aws s3 sync . s3://engagement-file-sandbox/ --no-progress --acl bucket-owner-full-control --follow-symlinks --delete