name: s3-deploy

on: workflow_dispatch
  # push:
  #   branches:    
  #     - main

jobs:
  deploy:
    name: Sync files to S3 Bucket
    # Run on self-hosted linux runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Sync files to S3 Bucket 
        run: aws s3 sync . s3://experience-file-sandbox/ \
          --exclude '.git'
          --exclude '.gitignore'
          --exclude 'package.json'
          --exclude '.github'
          --exclude '*.md'
          --follow-symlinks \
          --delete 