name: s3-deploy

on: 
  push:
    branches:    
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Sync files to S3 Bucket
    # Run on self-hosted linux runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Sync files to S3 Bucket 
        run: sh -x deploy.sh